# Generated by Django 3.1.8 on 2021-04-24 21:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=250, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Your Email')),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')], verbose_name='Your Pjone Number')),
                ('serv_date', models.DateField(null=True, verbose_name='Service Date')),
                ('service', models.CharField(choices=[('Concierge', 'Concierge Service'), ('Private', 'Private Jet Service'), ('Travel', 'Travel Management Service'), ('Event', 'Event Management Service'), ('Watercraft', 'Yatch/Watercraft Service'), ('Shopping', 'VIP Shopping Service'), ('Estate', 'Estate/Property Consultation Service'), ('Tickets', 'Event Tickets Service'), ('Other', 'Other Service')], default='Concierge', max_length=250, null=True, verbose_name='Select Service')),
                ('about_me', ckeditor.fields.RichTextField(verbose_name='About Yourself')),
                ('about_needs', ckeditor.fields.RichTextField(verbose_name='About Your Needs')),
                ('referals', models.CharField(blank=True, max_length=500, null=True, verbose_name='How did you find us?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
