# Generated by Django 3.1.8 on 2021-04-26 09:08

import django.core.validators
from django.db import migrations, models
import django_resized.forms
import leram.events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bg_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1280], upload_to=leram.events.models.events_file_path, verbose_name='Upload Event/Destination Background Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[345, 425], upload_to=leram.events.models.events_file_path, verbose_name='Upload Event/Destination Image'),
        ),
        migrations.AlterField(
            model_name='request',
            name='about_me',
            field=models.CharField(max_length=500, null=True, verbose_name='Brief info about you'),
        ),
        migrations.AlterField(
            model_name='request',
            name='about_needs',
            field=models.CharField(max_length=500, null=True, verbose_name='About Your Needs'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')], verbose_name='Your Phone Number'),
        ),
    ]
