# Generated by Django 3.1.8 on 2021-04-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210426_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration',
        ),
    ]
