# Generated by Django 3.1.8 on 2021-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booked',
        ),
        migrations.AddField(
            model_name='event',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Event Closed'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Have you booked'),
        ),
    ]
